class_name Constants

static var max_crank_degrees := 3.0 * 360.0
static var auto_crank_degrees_per_second := 3.0 * 360.0
static var max_speed := 1180.0
static var friction := 600.0
static var steer_speed := 200.0
static var enemy_speed := 200.0
static var enemy_kill_speed := 600.0
static var gear_time_bonus := 3.0
static var enemy_kill_time_bonus := 3.0
static var cannon_kill_time_bonus := 3.0
static var cannon_turret_speed_degrees := 200.0
static var bullet_speed := 400.0
static var default_level_time := 15.0
static var minion_respawn_delay := 2.0
static var hazard_spawner_interval := 3.0
static var hazard_spawner_hazard_count := 4
static var sub_boss_aim_duration := 3.0
static var sub_boss_crank_duration := 1.0
static var gear_spawner_interval := 3.0
static var gear_spawner_initial_count := 4
static var final_boss_dial_speed_degrees := 25.0
static var music_fade_seconds := 1.5
static var boss_intro_delay_seconds := 5.0
static var boss_intro_flicker_up_seconds := 1.0
static var boss_intro_flicker_down_seconds := 1.0
static var boss_intro_flicker_pause_seconds := 1.0
static var boss_intro_flicker_energy := 1.0
static var boss_intro_rise_seconds := 1.0
static var boss_intro_peak_energy := 0.0
static var boss_intro_glow_seconds := 2.0
static var boss_intro_glow_delay_seconds := 0.0
static var boss_intro_death_fade_seconds := 1.0
static var boss_intro_music_fade_seconds := 3.0
static var final_boss_victory_delay_seconds := 2.0
